language: go

go:
  - "1.11"
  - master
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxrandr-dev libxinerama-dev  libxinerama1 libx11-dev libxcursor-dev libxi-dev xorg-dev
  - git clone https://github.com/glfw/glfw && mkdir build && cd build && cmake ../glfw && make -j4 && sudo make install

script:
  - sh build.bat
